spring:
  application:
    name: backendsl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharedlearning
    username: root
    password: root
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 字段 => 下划线配对驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-prefix: 't_'

server:
  port: 8000
  servlet:
    context-path: /api

